# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x0f\x66raud_detection\".\n\x12\x66_detectionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\"*\n\x13\x66_detectionResponse\x12\x13\n\x0b\x66raudResult\x18\x01 \x01(\x08\x32l\n\x0f\x66raud_detection\x12Y\n\x0c\x66raud_detect\x12#.fraud_detection.f_detectionRequest\x1a$.fraud_detection.f_detectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_F_DETECTIONREQUEST']._serialized_start=42
  _globals['_F_DETECTIONREQUEST']._serialized_end=88
  _globals['_F_DETECTIONRESPONSE']._serialized_start=90
  _globals['_F_DETECTIONRESPONSE']._serialized_end=132
  _globals['_FRAUD_DETECTION']._serialized_start=134
  _globals['_FRAUD_DETECTION']._serialized_end=242
# @@protoc_insertion_point(module_scope)
